# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!

target 'AdyenRN' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Adyen'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'Adyen'
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.0'
      end
    end
  end
end
